import { StyleSheet, Platform } from 'react-native';
import { scaleWidth, scaleHeight, scaleFont } from '@utils';
import { FontWeight } from '@services';
import { Colors } from './constants/colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.BACKGROUND_LIGHT,
  },
  contentWrapper: {
    flex: 1,
    backgroundColor: '#FAFAFB',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: scaleWidth(16),
    paddingVertical: scaleHeight(12),
    backgroundColor: Colors.BACKGROUND_WHITE,
    borderBottomWidth: 1,
    borderBottomColor: Colors.BORDER_LIGHT, 
  },
  backButtonContainer: {
    width: scaleWidth(40),
    paddingVertical: 0,
    paddingHorizontal: 0,
    backgroundColor: Colors.TRANSPARENT,
  },
  backButton: {
    fontSize: scaleFont(22),
    color: Colors.TEXT_BLACK,
  },
  headerTitle: {
    fontSize: scaleFont(18),
    ...FontWeight.FONT_WEIGHT_700,
    color: Colors.TEXT_BLACK,
    textAlign: 'center',
  },
  headerRight: {
    width: scaleWidth(40),
  },
  searchSection: {
    paddingHorizontal: scaleWidth(16),
    paddingTop: scaleHeight(12),
    paddingBottom: scaleHeight(5),
  },
  searchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.BACKGROUND_WHITE,
    borderRadius: scaleWidth(8),
    paddingHorizontal: scaleWidth(12),
    height: scaleHeight(55),
    borderWidth: 1,
    borderColor: Colors.BORDER_LIGHT,
  },
  searchIcon: {
    width: scaleWidth(24),
    height: scaleWidth(24),
    marginRight: scaleWidth(8),
  },
  searchInput: {
    flex: 1,
    fontSize: scaleFont(14),
    color: Colors.TEXT_BLACK,
    paddingVertical: 0,
    ...(Platform.OS === 'android' && {
      includeFontPadding: false,
      textAlignVertical: 'center',
    }),
  },
  categoryScroll: {
    maxHeight: scaleHeight(70),
  },
  categoryContainer: {
    paddingLeft: scaleWidth(16),
    paddingRight: scaleWidth(16),
    paddingVertical: scaleHeight(12),
  },
  categoryButton: {
    paddingHorizontal: scaleWidth(24),
    borderRadius: scaleWidth(8),
    borderWidth: 1,
    borderColor: Colors.BORDER_LIGHT,
    backgroundColor: Colors.BACKGROUND_WHITE,
    marginRight: scaleWidth(12),
    justifyContent: 'center',
    alignItems: 'center',
    minHeight: scaleHeight(48),
  },
  categoryButtonLast: {
    marginRight: 0,
  },
  categoryButtonActive: {
    backgroundColor: '#15529A',
    borderColor: '#15529A',
  },
  categoryButtonText: {
    fontSize: scaleFont(13),
    color: Colors.TEXT_GRAY,
    textAlign: 'center',
    lineHeight: scaleFont(17),
    ...FontWeight.FONT_WEIGHT_400,
    ...(Platform.OS === 'android' && {
      includeFontPadding: false,
      textAlignVertical: 'center',
    }),
  },
  categoryButtonTextActive: {
    color: Colors.TEXT_WHITE,
    ...FontWeight.FONT_WEIGHT_500,
  },
  productList: {
    flex: 1,
    backgroundColor: Colors.BACKGROUND_WHITE,
  },
  productListContent: {
    paddingHorizontal: scaleWidth(16),
    backgroundColor: Colors.BACKGROUND_WHITE,
  },
  productItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: scaleHeight(16),
  },
  productInfo: {
    flex: 1,
    marginRight: scaleWidth(12),
    minWidth: 0,
  },
  productHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: scaleHeight(4),
    flexWrap: 'nowrap',
  },
  productName: {
    fontSize: scaleFont(14),
    ...FontWeight.FONT_WEIGHT_400,
    color: Colors.TEXT_DARK,
    marginRight: scaleWidth(6),
    flexShrink: 1,
  },
  rxTag: {
    backgroundColor: Colors.PRIMARY_BLUE_LIGHT,
    paddingHorizontal: scaleWidth(6),
    paddingVertical: scaleHeight(2),
    borderRadius: scaleWidth(4),
    flexShrink: 0,
    alignSelf: 'flex-start',
  },
  rxText: {
    fontSize: scaleFont(9),
    color: Colors.TEXT_WHITE,
    ...FontWeight.FONT_WEIGHT_500,
  },
  productCategory: {
    fontSize: scaleFont(12),
    color: Colors.TEXT_LIGHT_GRAY,
    marginBottom: scaleHeight(4),
  },
  productPrice: {
    fontSize: scaleFont(14),
    color: Colors.ACCENT_RED,
    ...FontWeight.FONT_WEIGHT_400,
  },
  quantitySelector: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: Colors.BORDER_LIGHT,
    borderRadius: scaleWidth(6),
    overflow: 'hidden',
  },
  quantityButton: {
    width: scaleWidth(36),
    height: scaleHeight(36),
    paddingVertical: 0,
    paddingHorizontal: 0,
    backgroundColor: Colors.BACKGROUND_WHITE,
    minWidth: 0,
  },
  quantityButtonText: {
    fontSize: scaleFont(16),
    color: Colors.PRIMARY_BLUE,
    ...FontWeight.FONT_WEIGHT_500,
  },
  quantityButtonDisabled: {
    color: Colors.DISABLED_GRAY,
  },
  quantityDisplay: {
    width: scaleWidth(40),
    height: scaleHeight(36),
    alignItems: 'center',
    justifyContent: 'center',
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderColor: Colors.BORDER_LIGHT,
    backgroundColor: Colors.BACKGROUND_QUANTITY,
  },
  quantityText: {
    fontSize: scaleFont(14),
    color: Colors.TEXT_BLACK,
    ...FontWeight.FONT_WEIGHT_500,
  },
  separator: {
    height: 1,
    backgroundColor: Colors.BORDER_LIGHT,
    marginLeft: 0,
    marginRight: 0,
  },
  categoryHeader: {
    backgroundColor: Colors.BACKGROUND_LIGHT,
    paddingVertical: scaleHeight(12),
    borderBottomWidth: 1,
    borderBottomColor: Colors.BORDER_LIGHT,
  },
  categoryHeaderText: {
    fontSize: scaleFont(18),
    ...FontWeight.FONT_WEIGHT_500,
    color: Colors.PRIMARY_BLUE,
  },
  bottomBar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: 'column',
    paddingHorizontal: scaleWidth(20),
    paddingTop: scaleHeight(16),
    backgroundColor: Colors.BACKGROUND_WHITE,
    borderTopWidth: 1,
    borderTopColor: Colors.BORDER_LIGHT,
    shadowColor: Colors.SHADOW_BLACK,
    shadowOffset: {
      width: 0,
      height: -2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 5,
    zIndex: 10,
  },
  summary: {
    marginBottom: scaleHeight(16),
  },
  summaryHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: scaleHeight(12),
    overflow: 'visible',
  },
  cartIconContainer: {
    position: 'relative',
    overflow: 'visible',
  },
  cartIconWrapper: {
    width: scaleWidth(40),
    height: scaleHeight(40),
    justifyContent: 'center',
    alignItems: 'center',
  },
  cartIcon: {
    width: scaleWidth(40),
    height: scaleHeight(40),
  },
  cartBadge: {
    position: 'absolute',
    top: scaleHeight(-8),
    right: scaleWidth(-16),
    backgroundColor: Colors.ACCENT_RED,
    borderRadius: scaleWidth(16),
    minWidth: scaleWidth(28),
    height: scaleHeight(28),
    paddingHorizontal: scaleWidth(8),
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: Colors.TEXT_WHITE,
    zIndex: 10,
  },
  cartBadgeText: {
    fontSize: scaleFont(7),
    ...FontWeight.FONT_WEIGHT_500,
    color: Colors.TEXT_WHITE,
    textAlign: 'center',
    lineHeight: scaleFont(12),
  },
  summaryTitle: {
    fontSize: scaleFont(14),
    ...FontWeight.FONT_WEIGHT_500,
    color: Colors.TEXT_DARK,
  },
  summaryDetails: {
    paddingLeft: 0,
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: scaleHeight(6),
  },
  summaryRowTotal: {
    marginTop: scaleHeight(8),
    paddingTop: scaleHeight(8),
    borderTopWidth: 1,
    borderTopColor: Colors.BORDER_LIGHT,
  },
  summaryLabel: {
    fontSize: scaleFont(13),
    color: Colors.TEXT_GRAY,
  },
  summaryValue: {
    fontSize: scaleFont(13),
    ...FontWeight.FONT_WEIGHT_400,
    color: Colors.TEXT_DARK,
  },
  summaryLabelTotal: {
    fontSize: scaleFont(14),
    ...FontWeight.FONT_WEIGHT_500,
    color: Colors.TEXT_DARK,
  },
  summaryValueTotal: {
    fontSize: scaleFont(16),
    ...FontWeight.FONT_WEIGHT_600,
    color: Colors.ACCENT_RED,
  },
  buttonContainer: {
    alignItems: 'flex-end',
    marginTop: scaleHeight(4),
  },
  reviewButton: {
    minWidth: scaleWidth(140),
    paddingHorizontal: scaleWidth(24),
    paddingVertical: scaleHeight(12),
    backgroundColor: Colors.PRIMARY_BLUE,
    borderRadius: scaleWidth(8),
  },
  emptyState: {
    alignItems: 'center',
    paddingHorizontal: scaleWidth(32),
    paddingTop: scaleHeight(40),
    paddingBottom: scaleHeight(20),
  },
  emptyStateTitle: {
    fontSize: scaleFont(16),
    ...FontWeight.FONT_WEIGHT_500,
    color: Colors.TEXT_DARK,
    marginBottom: scaleHeight(8),
    textAlign: 'center',
  },
  emptyStateMessage: {
    fontSize: scaleFont(13),
    color: Colors.TEXT_GRAY,
    textAlign: 'center',
    lineHeight: scaleFont(18),
  },
});
